# Generated by Django 2.2.11 on 2020-08-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('board_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
                ('no_of_elems', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('elem_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('estimation', models.DurationField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pwa.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pwa.User')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.Tab')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='participants',
            field=models.ManyToManyField(related_name='_board_participants_+', to='pwa.User'),
        ),
    ]
